from typing import Final

KEY_DELTA_T: Final[str] = "deltaT"

PIXEL_NUM_HORIZONTAL = 28
PIXEL_NUM_VERTICAL = 14
PIXEL_SIZE_HORIZONTAL = 97.6
PIXEL_SPACING_HORIZONTAL = 42.9
PIXEL_SIZE_VERTICAL = 161
PIXEL_SPACING_VERTICAL = 162.8

SCREEN_BASE_WIDTH = (
    PIXEL_NUM_HORIZONTAL * PIXEL_SIZE_HORIZONTAL
    + (PIXEL_NUM_HORIZONTAL - 1) * PIXEL_SPACING_HORIZONTAL
)
SCREEN_BASE_HEIGHT = (
    PIXEL_NUM_VERTICAL * PIXEL_SIZE_VERTICAL
    + (PIXEL_NUM_VERTICAL - 1) * PIXEL_SPACING_VERTICAL
)
