name: test-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner/test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.13"]
    steps:
      - uses: actions/checkout@v4
        name: Check those fine sneks out
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      - name: Fact checking
        run: python -m unittest discover --verbose -p "*_test.py" #python -m coverage run -m unittest discover --verbose -p "*_test.py"
      - name: Get Cover
        uses: orgoro/coverage@v3.2
        if: github.event_name == 'pull_request'
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
